#ifndef __DATA_DEFAULT_FONT_H__
#define __DATA_DEFAULT_FONT_H__

/*
 * data_default_font.h: Generated by img2gba.py version 3
 *
 * Copyright (C) 2005 Sakari Lehtonen <sakari@ionstream.fi>
 *
 */

enum DATA_DEFAULT_FONT_DEFS
{
	DATA_DEFAULT_FONT_LEN = 640
};

extern const unsigned int data_default_font[640];
extern const unsigned int data_default_font_pal[];

#endif /* __DATA_DEFAULT_FONT_H__ */
